// <auto-generated />
using BrsBlogWeb.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BrsBlogWeb.Migrations
{
    [DbContext(typeof(BrsBlogWebContext))]
    [Migration("20221022175208_DbInit")]
    partial class DbInit
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.17");

            modelBuilder.Entity("BrsBlogWeb.Models.BlogPost", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("post_description")
                        .HasColumnType("longtext");

                    b.Property<string>("post_header")
                        .HasColumnType("longtext");

                    b.Property<string>("post_img")
                        .HasColumnType("longtext");

                    b.Property<string>("post_keyword")
                        .HasColumnType("longtext");

                    b.Property<string>("post_url")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("BlogPost");
                });
#pragma warning restore 612, 618
        }
    }
}
